version: "3.8"

services:
  riding:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: riding-django
    command: ./start
    env_file:
      - ./.envs/.local/.django
    ports:
      - "8000:8000"
    depends_on:
      - postgis
      - redis
    
  postgis:
    image: postgis/postgis
    env_file:
      - ./.envs/.local/.postgis
    volumes:
      - riding_postgres_data:/var/lib/postgresql/data/
    container_name: riding-postgisdb

  redis:
    image: redis
    container_name: riding-redis

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: riding-celery-worker
    env_file:
      - ./.envs/.local/.django
    depends_on:
      - redis
      - riding
    command: ./start_celery_worker
  
  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    container_name: riding-celery-beat
    env_file:
      - ./.envs/.local/.django
    depends_on:
      - redis
      - riding
    command: ./start_celery_beat

volumes:
  riding_postgres_data: