# Generated by Django 4.2.7 on 2023-12-13 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0003_alter_vehicles_driver_alter_vehicles_year"),
        ("travels", "0002_requesttravel_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requesttravel",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="drivers.drivers",
            ),
        ),
    ]
