# Generated by Django 4.2.7 on 2023-12-13 23:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("travels", "0004_alter_requesttravel_created_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="requesttravel",
            name="driver",
        ),
        migrations.AlterField(
            model_name="requesttravel",
            name="created_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
