# Generated by Django 4.2.7 on 2023-12-27 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("travels", "0007_alter_requesttravel_expires_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="travel",
            name="request_travel",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="travel",
                to="travels.requesttravel",
            ),
        ),
    ]
