# Generated by Django 4.2.7 on 2023-12-27 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("travels", "0008_travel_request_travel"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="travel",
            name="prevent self traveling",
        ),
    ]
