# Generated by Django 4.2.7 on 2024-01-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travels", "0011_travel_vehicle"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmationtravel",
            name="check_driver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="confirmationtravel",
            name="check_user",
            field=models.BooleanField(default=False),
        ),
    ]
