# Generated by Django 4.2.7 on 2023-12-07 20:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drivers",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="is active"),
        ),
        migrations.CreateModel(
            name="Vehicles",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "plate_number",
                    models.CharField(max_length=10, verbose_name="plate number"),
                ),
                ("model", models.CharField(max_length=100, verbose_name="model")),
                ("year", models.IntegerField(default=2023, verbose_name="year")),
                ("color", models.CharField(max_length=100, verbose_name="color")),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="drivers.drivers",
                    ),
                ),
            ],
        ),
    ]
