# Generated by Django 4.2.7 on 2023-12-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("drivers", "0002_alter_drivers_is_active_vehicles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicles",
            name="driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="drivers.drivers",
            ),
        ),
        migrations.AlterField(
            model_name="vehicles",
            name="year",
            field=models.IntegerField(verbose_name="year"),
        ),
    ]
